### ISSUE TITLE
[Regression]: invite.gg is no longer working

### ISSUE THREAD

**Issue by piplupness** [PretendoNetwork/website#340] opened 2024-09-20 17:44 UTC
### Checked Existing

- [X] I have checked the repository for duplicate issues.

### What happened?

Clicking on the Discord logo brings to a non functional invite.gg link, HTTP 521

### What was the previous functionality?

Loading the Discord invite link as expected

### When did this occur?

Around 2 months ago according to this thread:
https://forum.pretendo.network/t/pretendo-discord-pink/1935/4?u=gamersinternatio

### Other relevant information. (OPTIONAL)

discord.gg/pretendo should work fine

**Comment by jonbarrow** [comment] 2024-09-24 16:35
Duplicate of https://github.com/PretendoNetwork/website/issues/339

**Closed by jonbarrow** 2024-09-24 16:35 UTC
Labels: awaiting-approval, regression
