### ISSUE TITLE
[Enhancement]: Add passwordrules to sign-up

### ISSUE THREAD

**Issue by MatthewL246** [PretendoNetwork/website#330] opened 2024-09-02 14:09 UTC
### Checked Existing

- [X] I have checked the repository for duplicate issues.

### What enhancement would you like to see?

Sometimes, users' password managers might generate passwords that will get rejected by the server because they use disallowed characters. This is annoying UX.

### Any other details to share? (OPTIONAL)

https://developer.1password.com/docs/web/compatible-website-design/#provide-password-requirements

https://developer.apple.com/documentation/security/customizing-password-autofill-rules

**Comment by jonbarrow** [comment] 2024-09-03 18:54
Is this a dupe of #164, or an extension of it? #164 only mentions Apple, but it *is* about password rules.

If this issue is meant to supersede #164 then we should close it.

#288 is also likely relevant here, though I never got a response back for what characters were causing issues. More research needs to be done on that.

**Comment by MatthewL246** [comment] 2024-09-03 21:20
Duplicate of #164

**Closed** 2024-09-03 21:21 UTC
Labels: enhancement, awaiting-approval
