### ISSUE TITLE
mii editor failing to save or load

### ISSUE THREAD

**Issue by mrjvs** [PretendoNetwork/website#154] opened 2022-09-20 15:34 UTC
few issues:
 - [ ] new accounts get invalid mii data
 - [ ] mii editor does a `http://` request instead of `//` so it cannot save
 - [x] api.pretendo.cc does not have a valid certificate, so will fail to save

to fix number 1, I recommend a modal that says something like "detected broken miidata [make new MII] [go back]"

---

encoded mii data from new accounts that doesnt work:
```
AwAAQOlVognnx0GC2qjhdwOzuI0n2QAAAGBqAHYAcwBqAHYAcwAyAAAAAAAAAEBAAAAhAQJoRBgmNEYUgRIXaA0AACkAUkhQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHwu
```

**Comment by ashmonty** [comment] 2022-09-20 16:10
I can confirm it works with my existing Mii, must be something to do with the default one

**Comment by mrjvs** [comment] 2022-09-22 22:39
fixed certificate issue

**Comment by jonbarrow** [comment] 2022-09-22 22:45
For the invalid Mii can you check the console? The updated Mii editor throws an error on invalid Mii data so it should show what the issue is

Curious there's an issue at all considering I ripped the default Mii data from real hardware? I just made a default Mii and copied its data

**Comment by mrjvs** [comment] 2022-09-22 22:58
> For the invalid Mii can you dev check the console? The updated Mii editor throws an error on invalid Mii data so it should show what the issue is
> 
> Curious there's an issue at all considering I ripped the default Mii data from real hardware? I just made a default Mii and copied its data

It says invalid checksum with a log with the encoded miidata included in the issue

**Comment by jonbarrow** [comment] 2022-09-23 17:39
Oh I know exactly why that happens. When registering a new account it asks for your preferred Mii name. On the account server it just inserts that name into the premade Mii data which includes a premade checksum

Since the name changed it means the checksum is no longer correct and the account server doesn't recalculate it

That needs to be fixed on the account server

An easy fix for that is to make a new `Mii` instance with valid Mii data and then change the name on the `Mii` object and then get the data from that. That will recalculate the checksum

**Closed** 2022-09-23 18:42 UTC
